# -*- coding: utf-8 -*-
"""Gaussian Naive Bayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vPa96IK3iFHVmp01ydtOfPIdew2YGHf-

#Exemplo de com usar o Algoritmo de Classificação Gaussian Naive Bayes

Neste exemplo vamos usar o dataset Iris.
Conjunto de dados de um grupo de plantas Iris, divididos em 3 espécies e 3 características. 


1.   Espécies: Iris setosa, Iris virginica e Iris versicolor
2.   Características: comprimento e largura das sépalas e pétalas
"""

# Importando as bibliotecas
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Gerando os dados com base no dataset 
X, y = load_iris(return_X_y=True)

#Fazendo a divisão dos dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)

#Imprimindo as dimensões
print('X_train:{0}\n'.format(X_train.shape))
print('X_test:{0}\n'.format(X_test.shape))
print('Y_train:{0}\n'.format(y_train.shape))
print('Y_test:{0}\n'.format(y_test.shape))

#Criando o modelo 
gnb = GaussianNB()

#Instanciando e treinando o modelo
modelo = gnb.fit(X_train, y_train)

#Fazendo a predição
y_pred = modelo.predict(X_test)

#Verificando a performace do modelo
acuracia = accuracy_score(y_test, y_pred)

print('Acurácia: {0}\n'.format(acuracia * 100))

